### ISSUE TITLE
SIGSEGV invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by shoan** [tailwarden/komiser#296]
**Describe the bug**
Komiser crashes with the following error:
```
INFO[2023-01-23T19:52:19+05:30] Fetched resources                             account=sil provider=AWS region=ap-south-1 resources=0 service=ELB
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x18505af]

goroutine 40 [running]:
github.com/tailwarden/komiser/providers/aws/efs.ElasticFileStorage({0x2093490, 0xc000130090}, {0xc0000db560, 0x0, {0x0, 0x0}, 0x0, 0x0, {0xc000042ed0, 0x5}})
        /go/src/github.com/tailwarden/komiser/providers/aws/efs/efs.go:37 +0x40f
github.com/tailwarden/komiser/providers/aws.FetchResources({0x2093490, 0xc000130090}, {0xc0000db560, 0x0, {0x0, 0x0}, 0x0, 0x0, {0xc000042ed0, 0x5}}, ...)
        /go/src/github.com/tailwarden/komiser/providers/aws/aws.go:67 +0x3ea
github.com/tailwarden/komiser/internal.fetchResources.func1({0x2093490?, 0xc000130090?}, {0xc0000db560, 0x0, {0x0, 0x0}, 0x0, 0x0, {0xc000042ed0, 0x5}}, ...)
        /go/src/github.com/tailwarden/komiser/internal/internal.go:138 +0x6b
created by github.com/tailwarden/komiser/internal.fetchResources
        /go/src/github.com/tailwarden/komiser/internal/internal.go:137 +0x6eb
```

**To Reproduce**
1.Start komiser with the ap-south-1 region filter using `./komiser start --regions ap-south-1`
2. After some resources are fetched, komiser crashes with the above error

**Expected behavior**
No crash

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 (WSL2 running on Windows 10 21H2)
 - Komiser version 3.0.0

**Comment by jakepage91** [comment]
Thanks a million for pointing this out @shoan. I'm going to get right on it.

**Comment by mlabouardy** [comment]
thanks @shoan the fix was addressed [here](https://github.com/tailwarden/komiser/commit/fe5ca56a2e0acb9e4add7d3befc7d3487c408a5a)

**Comment by HenriWilliams** [comment]
Hi, I'm seeing the same behaviour with Komiser crashing with the following error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1ecd3a1]
goroutine 67 [running]:
github.com/tailwarden/komiser/providers/aws/ec2.getEC2Relations(0xc01116f8f0, {0xc01291d140, 0x22})
	/home/runner/work/komiser/komiser/providers/aws/ec2/instances.go:202 +0x561
github.com/tailwarden/komiser/providers/aws/ec2.Instances({0x3b758a0, 0x5aa98c0}, {0xc00b3ff7a0, 0x0, {0x0, 0x0}, 0x0, 0x0, 0x0, 0x0, ...})
	/home/runner/work/komiser/komiser/providers/aws/ec2/instances.go:136 +0x111b
github.com/tailwarden/komiser/providers/aws.FetchResources.func1()
	/home/runner/work/komiser/komiser/providers/aws/aws.go:119 +0x99
github.com/tailwarden/komiser/providers.(*WorkerPool).worker(0xc00013b8c0)
	/home/runner/work/komiser/komiser/providers/providers.go:85 +0x3a
created by github.com/tailwarden/komiser/providers.(*WorkerPool).Start in goroutine 28
	/home/runner/work/komiser/komiser/providers/providers.go:69 +0x25
```

I'm seeing this behaviour when running the `3.1.5` version of the Komiser Docker container on multiple AWS accounts.
